apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    # env:
    #   - name: JAVA_OPTS
    #     valueFrom:
    #       configMapKeyRef:
    #         name: dhis2.conf
    #         key: JAVA_OPTS:wq
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    # volumeMounts:
    #   - name: dhis2-configuration
    #     mountPath: /opt/dhis2/dhis.conf
    #     subPath: dhis.conf

    #   - name: dhis2-configuration
    #     mountPath: /opt/dhis2/log4j2.xml
    #     subPath: log4j2.xml 
          
  # restartPolicy: Always
  # volumes:
    # - name: dhis2-configuration
    #   configMap:
    #     name: dhis2-configuration
    #     # items:
    #     # - key: dhis.conf
    #     #   path: dhis.conf 
    #     # - key: log4j2.xml
    #     #   path: log4j2.xml 
