---
- hosts: control_plane
  tasks:
    - name: initialize the cluster
      become: True
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: /home/ktito/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ktito/.kube/config
        remote_src: yes
        owner: ktito

    - name: install Pod network
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
