apiVersion: v1
kind: PersistentVolume 
metadata:
  name: db-dumpi-pv  
  labels:
    type: local 
    # app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql" 
