apiVersion: v1
kind: PersistentVolume 
metadata:
  name: db-dump 
  labels:
    type: local 
    app: postgres1
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql" 
